name: SuperSpleef
author: SpleefLeague
main: net.spleefleague.superspleef.SuperSpleef
version: 1.0
depend: [SpleefLeagueCore]
commands:    
    spleef:
        description: SuperSpleef queue command
        aliases: [s]
        usage: |
          /<command> [arena]
    reset:
        description: Resets the current spleef field
        usage:
            /<command> [player]
#    joinswc:
#        description: Join the SWC
#        usage:
#            /<command>