name: SuperSpleef
author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
main: com.spleefleague.superspleef.SuperSpleef
version: 1.0
depend: [SpleefLeagueCore]
loadbefore: [SuperJump]
commands:    
    spleef:
        description: SuperSpleef queue command
        aliases: [s]
        usage: |
          /<command> [arena]
    multispleef:
        description: MultiSpleef queue command
        aliases: [ms]
        usage: |
          /<command> [arena]
    reset:
        description: Resets the current spleef field
        usage:
            /<command> [player]
    joinswc:
        description: Join the SWC
        usage:
            /<command>
    playto:
        description: Changes amount of wins needed to be reached to completely win the game
        usage:
            /<command> [wins]